#!/bin/sh

# Some aliases
alias v="nvim"
alias abook="abook -C $HOME/.config/abook/abookrc --datafile $HOME/docs/contacts/addressbook"
alias eslint="./node_modules/.bin/eslint"
alias ls="ls -hN --color=auto --group-directories-first"
alias tmux="tmux -f $HOME/.config/tmux/tmux.conf"
alias units="units -H ''"
weath() { curl wttr.in/$1 ;} # Check the weather (give city or leave blank).
corona() { curl https://corona-stats.online/$1 ;} # It's corona time
wintitle() { printf "\033]2;%s\a" "$1";}

# Generic shortcuts
alias music="ncmpcpp"
alias clock="ncmpcpp -s clock"
alias news="newsboat"
alias files="ranger"
alias audio="ncpamixer"
alias calendar="calcurse"
alias contacts="abook"
alias calc="R --no-save"

# Mounting drive shortcuts
alias mnt="udisksctl mount -b"
alias umnt="udisksctl unmount -b"
alias dlock="udisksctl lock -b"
alias dulock="udisksctl unlock -b"

# Internet
alias yt="youtube-dl --add-metadata -ic" # Download video link
alias yta="youtube-dl --add-metadata -xic" # Download only audio
alias YT="youtube-viewer"
alias starwars="telnet towel.blinkenlights.nl"

# Audio and Music
alias mute="lmc mute"
alias vu="lmc up"
alias vd="lmc down"
alias play="mpc toggle"
alias next="mpc next"
alias prev="mpc prev"
alias pause="mpc pause"
alias beg="mpc seek 0%"
alias lilbak="mpc seek -10"
alias lilfor="mpc seek +10"
alias bigbak="mpc seek -120"
alias bigfor="mpc seek +120"

