#!/bin/sh

if ! [ -z $(swaymsg -t get_tree | grep 'quakemite') ]; then
    if [ -z $(swaymsg -t get_tree | grep -A 42 'quakemite' | tail -n 1 | grep 'true') ]; then
        swaymsg '[title="quakemite"] scratchpad show'
    else
        swaymsg '[title="quakemite"] move scratchpad'
    fi
else
    $TERMINAL -t "quakemite" -e "$SHELL -c 'TERM=st; TERMINAL=termite; tmux a || tmux'"
fi

