#!/bin/sh

if pidof telegram-desktop > /dev/null; then
    if [ -z $(swaymsg -t get_tree | grep -A 1 'telegramdesktop' | tail -n 1 | grep 'true') ]; then
        swaymsg '[app_id="telegramdesktop"] scratchpad show'
    else
        swaymsg '[app_id="telegramdesktop"] move scratchpad'
    fi
else
    telegram-desktop
fi

