#!/bin/sh

if pidof vk > /dev/null; then
    if [ -z $(swaymsg -t get_tree | grep -B 5 'vk' | head -n 1 | grep 'true') ]; then
        swaymsg '[instance="vk"] scratchpad show'
    else
        swaymsg '[instance="vk"] move scratchpad'
    fi
else
    xway vk-messenger
fi

