#!/bin/sh

# Terminate already running mako instance
killall -q mako

# Wait until the processes have been shut down
while pgrep -u $UID -x mako >/dev/null; do sleep 1; done

mako --background-color "#1a1a1acc" --border-color "#000000" --default-timeout 5000 --height 300
