#!/bin/sh
# A dmenu binary prompt script.
# Gives a dmenu prompt labeled with $1 to perform command $2.
# For example:
# `./prompt "Do you want to shutdown?" "shutdown -h now"`

[ "$(printf "No\\nYes" | bemenu -i -p "$1" --nb darkred --hb red --hf white -nf gray )" = "Yes" ] && $2
