#!/bin/sh
# Change audio output for all streams and set as default using dmenu

# Source settings from .bemenurc
. $HOME/.bemenurc

output=$(listsinks | bemenu -p "Select audio output: " $BEMENU_OPTIONS)

[ "$output" != "" ] || exit

changeoutput $output

notify-send "🔉 Audio output switched" "Audio output switched to '$output'"
