#!/bin/sh

# Gives a dmenu prompt to search DuckDuckGo.
# Without input, will open DuckDuckGo.com.
# Anything else, it search it.

# Source settings from .bemenurc
. $HOME/.bemenurc

pgrep -x dmenu && exit

choice=$(echo "" | bemenu -i -p "Search DuckDuckGo:" $BEMENU_OPTIONS) || exit 1

if [ "$choice" = ""  ]; then
	$BROWSER "https://duckduckgo.com"
else
	$BROWSER "https://duckduckgo.com/?q=$choice&t=ffab&atb=v1-1"
fi
