#!/bin/sh
# Change audio output for all streams and set as default using dmenu

# Source settings from .bemenurc
. $HOME/.bemenurc

output=$(listsinks | bemenu -p "Select audio output: " --tf="$BEMENU_TF" --tb="$BEMENU_NB" --fb="$BEMENU_NB" --fn="$BEMENU_FN" --nb="$BEMENU_NB" --nf="$BEMENU_NF" --hf="$BEMENU_HF" --hb="$BEMENU_HB")

[ "$output" != "" ] || exit

changeoutput $output

notify-send "🔉 Audio output switched" "Audio output switched to '$output'"
